// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview AI agent that generates a credit score for a member based on their contribution and repayment history.
 *
 * - generateCreditScore - A function that generates a credit score for a member.
 * - GenerateCreditScoreInput - The input type for the generateCreditScore function.
 * - GenerateCreditScoreOutput - The return type for the generateCreditScore function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateCreditScoreInputSchema = z.object({
  contributionHistory: z
    .string()
    .describe(
      'The contribution history of the member, including dates and amounts contributed.'
    ),
  repaymentHistory: z
    .string()
    .describe(
      'The repayment history of the member, including dates and amounts repaid.'
    ),
  memberId: z.string().describe('The unique identifier of the member.'),
});
export type GenerateCreditScoreInput = z.infer<typeof GenerateCreditScoreInputSchema>;

const GenerateCreditScoreOutputSchema = z.object({
  creditScore: z
    .number()
    .describe(
      'A numeric credit score representing the creditworthiness of the member.'
    ),
  reasoning: z
    .string()
    .describe(
      'The reasoning behind the assigned credit score, based on the provided history.'
    ),
});
export type GenerateCreditScoreOutput = z.infer<typeof GenerateCreditScoreOutputSchema>;

export async function generateCreditScore(input: GenerateCreditScoreInput): Promise<GenerateCreditScoreOutput> {
  return generateCreditScoreFlow(input);
}

const generateCreditScorePrompt = ai.definePrompt({
  name: 'generateCreditScorePrompt',
  input: {schema: GenerateCreditScoreInputSchema},
  output: {schema: GenerateCreditScoreOutputSchema},
  prompt: `You are an AI assistant that generates credit scores for SACCO members.

  Given the contribution and repayment history of a member, generate a credit score between 0 and 100.
  Also, provide a brief explanation of your reasoning for the assigned score.

  Member ID: {{{memberId}}}
  Contribution History: {{{contributionHistory}}}
  Repayment History: {{{repaymentHistory}}}

  Consider these factors when creating the credit score and reasoning:
  - Timeliness of contributions and repayments
  - Consistency of contributions and repayments
  - Length of membership
  - Any defaults or late payments
`,
});

const generateCreditScoreFlow = ai.defineFlow(
  {
    name: 'generateCreditScoreFlow',
    inputSchema: GenerateCreditScoreInputSchema,
    outputSchema: GenerateCreditScoreOutputSchema,
  },
  async input => {
    const {output} = await generateCreditScorePrompt(input);
    return output!;
  }
);
